<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Photo extends Model
{
    protected $guarded=[]; //deshabilitamos la proteccion de asignacion masiva

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function($photo){
            Storage::disk('public')->delete($photo->url);
        });
    }
}
